services:
  qdrant:
    image: qdrant/qdrant:v1.11.0  # usar Docker Hub (tag existente)
    restart: unless-stopped
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  search-service:
    container_name: search-service
    build: ./search-service
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - default
      - n8n_net
      - svc_net                               # <— entra na rede compartilhada
      
volumes:
  qdrant_data:

networks:
  svc_net:
    external: true                            # <— usa a rede já criada no host