name: Deploy to VPS (Hostinger)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/opt/realestate-search"
          rm: true
          overwrite: true

      - name: Remote deploy (docker compose up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: OPENAI_API_KEY,EMBEDDING_MODEL,VECTOR_SIZE,QDRANT_URL,QDRANT_COLLECTION,DOCDB_URI,DB_NAME,COLLECTION_NAME,VECTOR_DB_URL,DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          script: |
            set -e
            cd /opt/realestate-search
            rm -rf .git .github/.DS_Store || true

            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
            fi
            if ! docker compose version >/dev/null 2>&1; then
              apt-get update && apt-get install -y docker-compose-plugin || true
            fi

            # Sanity check
            required=(OPENAI_API_KEY EMBEDDING_MODEL VECTOR_SIZE QDRANT_URL QDRANT_COLLECTION DOCDB_URI DB_NAME COLLECTION_NAME VECTOR_DB_URL)
            for v in "${required[@]}"; do
              if [ -z "${!v}" ]; then
                echo "[ERRO] Secret $v não definido no GitHub Actions." >&2
                exit 1
              fi
            done

            # .env
            cat > .env <<EOF
            OPENAI_API_KEY=${OPENAI_API_KEY}
            EMBEDDING_MODEL=${EMBEDDING_MODEL}
            VECTOR_SIZE=${VECTOR_SIZE}
            QDRANT_URL=${QDRANT_URL}
            QDRANT_COLLECTION=${QDRANT_COLLECTION}
            DOCDB_URI=${DOCDB_URI}
            DB_NAME=${DB_NAME}
            COLLECTION_NAME=${COLLECTION_NAME}
            VECTOR_DB_URL=${VECTOR_DB_URL}
            EOF

            # Login Docker Hub (evita rate limit)
            if [ -n "${DOCKERHUB_USERNAME}" ] && [ -n "${DOCKERHUB_TOKEN}" ]; then
              echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || true
            fi

            # Pre-pull direto do Docker Hub para evitar mismatch de registry/tag
            docker pull qdrant/qdrant:v1.11.0 || true

            docker compose up -d --build
            docker ps --format '{{.Names}} -> {{.Status}}'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          VECTOR_SIZE: ${{ secrets.VECTOR_SIZE }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_COLLECTION: ${{ secrets.QDRANT_COLLECTION }}
          DOCDB_URI: ${{ secrets.DOCDB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          VECTOR_DB_URL: ${{ secrets.VECTOR_DB_URL }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}