name: Deploy to VPS (Hostinger)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/opt/realestate-search"
          rm: true
          overwrite: true

      - name: Remote deploy (docker compose up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /opt/realestate-search
            # (Opcional) limpeza
            rm -rf .git .github/.DS_Store || true
            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
            fi
            if ! docker compose version >/dev/null 2>&1; then
              apt-get update && apt-get install -y docker-compose-plugin || true
            fi
            # Login no Docker Hub (evita rate limit). Se variáveis não existirem, ignora.
            if [ -n "${DOCKERHUB_USERNAME}" ] && [ -n "${DOCKERHUB_TOKEN}" ]; then
              echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || true
            fi
            if [ ! -f .env ]; then
              cp .env.example .env
              echo "[WARN] .env criado a partir do exemplo. Preencha variáveis e re-subir." >&2
            fi
            # "docker compose pull" pode falhar por rate limit; seguimos para up -d --build
            docker compose up -d --build
            docker ps --format '{{.Names}} -> {{.Status}}'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}